int BoxA = 5, BoxB = 10;
int sum = BoxA + BoxB;
int dif = BoxA - BoxB;
int multipli = BoxA * BoxB;
int division = BoxA % BoxB;
Console.WriteLine(BoxA + " + " + BoxB + " = " + sum);
Console.WriteLine(BoxA + " - " + BoxB + " = " + dif);
Console.WriteLine(BoxA + " * " + BoxB + " = " + multipli);
Console.WriteLine(BoxA + " % " + BoxB + " = " + division);
Console.WriteLine("ta daa");
Console.ReadLine();
